import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const colleges = [
  {
    name: "IIT Bombay",
    location: "Mumbai",
    state: "Maharashtra",
    fees: 245000,
    rating: 4.9,
    placement_percent: 96,
    courses: ["B.Tech", "M.Tech", "MBA"],
    description: "Premier institute known for research excellence and strong global placements.",
    image_url: "https://images.example.com/iit-bombay.jpg",
    exam_accepted: "JEE",
    min_rank: 1,
    max_rank: 1200
  },
  {
    name: "IIT Delhi",
    location: "New Delhi",
    state: "Delhi",
    fees: 240000,
    rating: 4.9,
    placement_percent: 95,
    courses: ["B.Tech", "M.Tech", "MBA"],
    description: "Top engineering institution with innovation-driven curriculum and startup culture.",
    image_url: "https://images.example.com/iit-delhi.jpg",
    exam_accepted: "JEE",
    min_rank: 1,
    max_rank: 1500
  },
  {
    name: "IIT Madras",
    location: "Chennai",
    state: "Tamil Nadu",
    fees: 235000,
    rating: 4.8,
    placement_percent: 94,
    courses: ["B.Tech", "M.Tech", "MS"],
    description: "Research-focused IIT with excellent faculty and strong core engineering programs.",
    image_url: "https://images.example.com/iit-madras.jpg",
    exam_accepted: "JEE",
    min_rank: 1,
    max_rank: 1600
  },
  {
    name: "IIT Kanpur",
    location: "Kanpur",
    state: "Uttar Pradesh",
    fees: 230000,
    rating: 4.8,
    placement_percent: 93,
    courses: ["B.Tech", "M.Tech", "MBA"],
    description: "Known for academic rigor, computing research and high quality campus life.",
    image_url: "https://images.example.com/iit-kanpur.jpg",
    exam_accepted: "JEE",
    min_rank: 1,
    max_rank: 1800
  },
  {
    name: "IIT Kharagpur",
    location: "Kharagpur",
    state: "West Bengal",
    fees: 225000,
    rating: 4.7,
    placement_percent: 92,
    courses: ["B.Tech", "M.Tech", "LLB"],
    description: "Historic IIT with broad interdisciplinary offerings and strong alumni network.",
    image_url: "https://images.example.com/iit-kharagpur.jpg",
    exam_accepted: "JEE",
    min_rank: 1,
    max_rank: 2200
  },
  {
    name: "IIT Roorkee",
    location: "Roorkee",
    state: "Uttarakhand",
    fees: 220000,
    rating: 4.7,
    placement_percent: 91,
    courses: ["B.Tech", "M.Tech", "MBA"],
    description: "Strong in civil and core engineering disciplines with excellent placements.",
    image_url: "https://images.example.com/iit-roorkee.jpg",
    exam_accepted: "JEE",
    min_rank: 200,
    max_rank: 2500
  },
  {
    name: "IIT Guwahati",
    location: "Guwahati",
    state: "Assam",
    fees: 215000,
    rating: 4.6,
    placement_percent: 89,
    courses: ["B.Tech", "M.Tech", "B.Des"],
    description: "Scenic campus with growing research output and modern curriculum.",
    image_url: "https://images.example.com/iit-guwahati.jpg",
    exam_accepted: "JEE",
    min_rank: 400,
    max_rank: 3200
  },
  {
    name: "IIT Hyderabad",
    location: "Hyderabad",
    state: "Telangana",
    fees: 210000,
    rating: 4.6,
    placement_percent: 90,
    courses: ["B.Tech", "M.Tech", "M.Des"],
    description: "Emerging IIT with advanced labs and strong ties to tech industry.",
    image_url: "https://images.example.com/iit-hyderabad.jpg",
    exam_accepted: "JEE",
    min_rank: 500,
    max_rank: 3600
  },
  {
    name: "NIT Trichy",
    location: "Tiruchirappalli",
    state: "Tamil Nadu",
    fees: 180000,
    rating: 4.6,
    placement_percent: 91,
    courses: ["B.Tech", "M.Tech", "MBA"],
    description: "Top NIT with consistent placements and strong engineering academics.",
    image_url: "https://images.example.com/nit-trichy.jpg",
    exam_accepted: "JEE",
    min_rank: 1200,
    max_rank: 8000
  },
  {
    name: "NIT Surathkal",
    location: "Mangaluru",
    state: "Karnataka",
    fees: 175000,
    rating: 4.5,
    placement_percent: 89,
    courses: ["B.Tech", "M.Tech", "MCA"],
    description: "Well-known coastal campus with strong CS and electronics programs.",
    image_url: "https://images.example.com/nit-surathkal.jpg",
    exam_accepted: "JEE",
    min_rank: 1500,
    max_rank: 9500
  },
  {
    name: "NIT Warangal",
    location: "Warangal",
    state: "Telangana",
    fees: 170000,
    rating: 4.5,
    placement_percent: 88,
    courses: ["B.Tech", "M.Tech", "MBA"],
    description: "Highly reputed NIT with strong placement and coding culture.",
    image_url: "https://images.example.com/nit-warangal.jpg",
    exam_accepted: "JEE",
    min_rank: 1800,
    max_rank: 10500
  },
  {
    name: "NIT Rourkela",
    location: "Rourkela",
    state: "Odisha",
    fees: 165000,
    rating: 4.4,
    placement_percent: 86,
    courses: ["B.Tech", "M.Tech", "MSc"],
    description: "Known for metallurgy and broad engineering opportunities.",
    image_url: "https://images.example.com/nit-rourkela.jpg",
    exam_accepted: "JEE",
    min_rank: 2200,
    max_rank: 12000
  },
  {
    name: "NIT Calicut",
    location: "Kozhikode",
    state: "Kerala",
    fees: 160000,
    rating: 4.4,
    placement_percent: 85,
    courses: ["B.Tech", "M.Tech", "MBA"],
    description: "Strong academics with good research and balanced campus life.",
    image_url: "https://images.example.com/nit-calicut.jpg",
    exam_accepted: "JEE",
    min_rank: 2600,
    max_rank: 13500
  },
  {
    name: "BITS Pilani",
    location: "Pilani",
    state: "Rajasthan",
    fees: 820000,
    rating: 4.8,
    placement_percent: 93,
    courses: ["B.E.", "M.E.", "MBA"],
    description: "Leading private engineering university with flexible academic structure.",
    image_url: "https://images.example.com/bits-pilani.jpg",
    exam_accepted: "JEE",
    min_rank: 1800,
    max_rank: 11000
  },
  {
    name: "IIIT Hyderabad",
    location: "Hyderabad",
    state: "Telangana",
    fees: 420000,
    rating: 4.8,
    placement_percent: 95,
    courses: ["B.Tech", "M.Tech", "MS"],
    description: "Elite institute for computer science and artificial intelligence research.",
    image_url: "https://images.example.com/iiit-hyderabad.jpg",
    exam_accepted: "JEE",
    min_rank: 500,
    max_rank: 4000
  },
  {
    name: "IIIT Bangalore",
    location: "Bengaluru",
    state: "Karnataka",
    fees: 380000,
    rating: 4.6,
    placement_percent: 92,
    courses: ["B.Tech", "M.Tech", "MSc"],
    description: "Industry-oriented programs with strong software placements.",
    image_url: "https://images.example.com/iiit-bangalore.jpg",
    exam_accepted: "JEE",
    min_rank: 2500,
    max_rank: 9000
  },
  {
    name: "Vellore Institute of Technology",
    location: "Vellore",
    state: "Tamil Nadu",
    fees: 320000,
    rating: 4.3,
    placement_percent: 87,
    courses: ["B.Tech", "M.Tech", "MBA"],
    description: "Large private university with diverse engineering specializations.",
    image_url: "https://images.example.com/vit.jpg",
    exam_accepted: "JEE",
    min_rank: 7000,
    max_rank: 60000
  },
  {
    name: "SRM Institute of Science and Technology",
    location: "Chennai",
    state: "Tamil Nadu",
    fees: 350000,
    rating: 4.2,
    placement_percent: 84,
    courses: ["B.Tech", "M.Tech", "MBA"],
    description: "Popular private university with strong industry collaborations.",
    image_url: "https://images.example.com/srm.jpg",
    exam_accepted: "JEE",
    min_rank: 9000,
    max_rank: 75000
  },
  {
    name: "Manipal Institute of Technology",
    location: "Manipal",
    state: "Karnataka",
    fees: 430000,
    rating: 4.3,
    placement_percent: 85,
    courses: ["B.Tech", "M.Tech", "MBA"],
    description: "Well-established private institution with modern labs and campus life.",
    image_url: "https://images.example.com/mit-manipal.jpg",
    exam_accepted: "JEE",
    min_rank: 8500,
    max_rank: 70000
  },
  {
    name: "Thapar Institute of Engineering and Technology",
    location: "Patiala",
    state: "Punjab",
    fees: 390000,
    rating: 4.3,
    placement_percent: 86,
    courses: ["B.Tech", "M.Tech", "MBA"],
    description: "Respected private engineering institute with robust placement support.",
    image_url: "https://images.example.com/thapar.jpg",
    exam_accepted: "JEE",
    min_rank: 6000,
    max_rank: 50000
  },
  {
    name: "Amrita Vishwa Vidyapeetham",
    location: "Coimbatore",
    state: "Tamil Nadu",
    fees: 300000,
    rating: 4.2,
    placement_percent: 82,
    courses: ["B.Tech", "M.Tech", "MBA"],
    description: "Multidisciplinary campus with strong focus on ethics and innovation.",
    image_url: "https://images.example.com/amrita.jpg",
    exam_accepted: "JEE",
    min_rank: 11000,
    max_rank: 80000
  },
  {
    name: "RV College of Engineering",
    location: "Bengaluru",
    state: "Karnataka",
    fees: 250000,
    rating: 4.4,
    placement_percent: 88,
    courses: ["B.E.", "M.Tech", "MCA"],
    description: "Top Karnataka engineering college with strong alumni and placements.",
    image_url: "https://images.example.com/rvce.jpg",
    exam_accepted: "JEE",
    min_rank: 12000,
    max_rank: 90000
  },
  {
    name: "PSG College of Technology",
    location: "Coimbatore",
    state: "Tamil Nadu",
    fees: 175000,
    rating: 4.3,
    placement_percent: 86,
    courses: ["B.E.", "M.E.", "MBA"],
    description: "Legacy engineering college with excellent industrial exposure.",
    image_url: "https://images.example.com/psg-tech.jpg",
    exam_accepted: "JEE",
    min_rank: 13000,
    max_rank: 95000
  },
  {
    name: "COEP Technological University",
    location: "Pune",
    state: "Maharashtra",
    fees: 95000,
    rating: 4.5,
    placement_percent: 87,
    courses: ["B.Tech", "M.Tech", "MBA"],
    description: "Historic public engineering institution with strong core departments.",
    image_url: "https://images.example.com/coep.jpg",
    exam_accepted: "JEE",
    min_rank: 5000,
    max_rank: 40000
  },
  {
    name: "Jadavpur University Faculty of Engineering",
    location: "Kolkata",
    state: "West Bengal",
    fees: 50000,
    rating: 4.6,
    placement_percent: 88,
    courses: ["B.E.", "M.E.", "PhD"],
    description: "Highly competitive public engineering faculty with low fees and high ROI.",
    image_url: "https://images.example.com/jadavpur.jpg",
    exam_accepted: "JEE",
    min_rank: 4500,
    max_rank: 35000
  },
  {
    name: "Delhi Technological University",
    location: "New Delhi",
    state: "Delhi",
    fees: 210000,
    rating: 4.5,
    placement_percent: 89,
    courses: ["B.Tech", "M.Tech", "MBA"],
    description: "Premier Delhi state university with excellent coding and placement ecosystem.",
    image_url: "https://images.example.com/dtu.jpg",
    exam_accepted: "JEE",
    min_rank: 3000,
    max_rank: 30000
  },
  {
    name: "Netaji Subhas University of Technology",
    location: "New Delhi",
    state: "Delhi",
    fees: 205000,
    rating: 4.4,
    placement_percent: 87,
    courses: ["B.Tech", "M.Tech", "MBA"],
    description: "Strong engineering university with growing industry partnerships.",
    image_url: "https://images.example.com/nsut.jpg",
    exam_accepted: "JEE",
    min_rank: 5000,
    max_rank: 42000
  },
  {
    name: "PES University",
    location: "Bengaluru",
    state: "Karnataka",
    fees: 450000,
    rating: 4.2,
    placement_percent: 84,
    courses: ["B.Tech", "M.Tech", "MBA"],
    description: "Private tech-focused university with strong links to Bengaluru companies.",
    image_url: "https://images.example.com/pes.jpg",
    exam_accepted: "JEE",
    min_rank: 14000,
    max_rank: 100000
  },
  {
    name: "SASTRA Deemed University",
    location: "Thanjavur",
    state: "Tamil Nadu",
    fees: 190000,
    rating: 4.1,
    placement_percent: 80,
    courses: ["B.Tech", "M.Tech", "MBA"],
    description: "Well-regarded engineering programs with value-for-money fee structure.",
    image_url: "https://images.example.com/sastra.jpg",
    exam_accepted: "JEE",
    min_rank: 18000,
    max_rank: 120000
  },
  {
    name: "Kalinga Institute of Industrial Technology",
    location: "Bhubaneswar",
    state: "Odisha",
    fees: 280000,
    rating: 4.1,
    placement_percent: 79,
    courses: ["B.Tech", "M.Tech", "MBA"],
    description: "Large private campus with broad engineering and management offerings.",
    image_url: "https://images.example.com/kiit.jpg",
    exam_accepted: "JEE",
    min_rank: 22000,
    max_rank: 150000
  },

  {
    name: "AIIMS New Delhi",
    location: "New Delhi",
    state: "Delhi",
    fees: 60000,
    rating: 5.0,
    placement_percent: 98,
    courses: ["MBBS", "MD", "MS"],
    description: "India's premier medical institute with top faculty and clinical exposure.",
    image_url: "https://images.example.com/aiims-delhi.jpg",
    exam_accepted: "NEET",
    min_rank: 1,
    max_rank: 60
  },
  {
    name: "PGIMER Chandigarh",
    location: "Chandigarh",
    state: "Chandigarh",
    fees: 85000,
    rating: 4.9,
    placement_percent: 97,
    courses: ["MBBS", "MD", "DM"],
    description: "High-end tertiary care institute known for advanced medical training.",
    image_url: "https://images.example.com/pgimer.jpg",
    exam_accepted: "NEET",
    min_rank: 20,
    max_rank: 180
  },
  {
    name: "CMC Vellore",
    location: "Vellore",
    state: "Tamil Nadu",
    fees: 120000,
    rating: 4.9,
    placement_percent: 96,
    courses: ["MBBS", "MD", "MS"],
    description: "Top private medical college with excellent patient load and research.",
    image_url: "https://images.example.com/cmc-vellore.jpg",
    exam_accepted: "NEET",
    min_rank: 80,
    max_rank: 450
  },
  {
    name: "JIPMER Puducherry",
    location: "Puducherry",
    state: "Puducherry",
    fees: 90000,
    rating: 4.8,
    placement_percent: 95,
    courses: ["MBBS", "MD", "MS"],
    description: "Highly reputed government medical institute with strong academics.",
    image_url: "https://images.example.com/jipmer.jpg",
    exam_accepted: "NEET",
    min_rank: 100,
    max_rank: 600
  },
  {
    name: "KGMU Lucknow",
    location: "Lucknow",
    state: "Uttar Pradesh",
    fees: 110000,
    rating: 4.7,
    placement_percent: 93,
    courses: ["MBBS", "BDS", "MD"],
    description: "Major state medical university with diverse clinical departments.",
    image_url: "https://images.example.com/kgmu.jpg",
    exam_accepted: "NEET",
    min_rank: 500,
    max_rank: 2000
  },
  {
    name: "Maulana Azad Medical College",
    location: "New Delhi",
    state: "Delhi",
    fees: 80000,
    rating: 4.8,
    placement_percent: 95,
    courses: ["MBBS", "MD", "MS"],
    description: "Prestigious Delhi government college with strong residency outcomes.",
    image_url: "https://images.example.com/mamc.jpg",
    exam_accepted: "NEET",
    min_rank: 250,
    max_rank: 1300
  },
  {
    name: "Grant Medical College",
    location: "Mumbai",
    state: "Maharashtra",
    fees: 100000,
    rating: 4.6,
    placement_percent: 92,
    courses: ["MBBS", "MD", "MS"],
    description: "Historic Mumbai medical college attached to leading teaching hospitals.",
    image_url: "https://images.example.com/grant-medical.jpg",
    exam_accepted: "NEET",
    min_rank: 850,
    max_rank: 3800
  },
  {
    name: "Madras Medical College",
    location: "Chennai",
    state: "Tamil Nadu",
    fees: 95000,
    rating: 4.7,
    placement_percent: 93,
    courses: ["MBBS", "MD", "MS"],
    description: "One of the oldest medical colleges with robust clinical infrastructure.",
    image_url: "https://images.example.com/mmc-chennai.jpg",
    exam_accepted: "NEET",
    min_rank: 900,
    max_rank: 4200
  },
  {
    name: "B.J. Medical College Ahmedabad",
    location: "Ahmedabad",
    state: "Gujarat",
    fees: 100000,
    rating: 4.5,
    placement_percent: 91,
    courses: ["MBBS", "MD", "MS"],
    description: "Reputed government college with strong emergency and specialty exposure.",
    image_url: "https://images.example.com/bjmc-ahmedabad.jpg",
    exam_accepted: "NEET",
    min_rank: 1300,
    max_rank: 6000
  },
  {
    name: "Seth GS Medical College",
    location: "Mumbai",
    state: "Maharashtra",
    fees: 115000,
    rating: 4.6,
    placement_percent: 92,
    courses: ["MBBS", "MD", "MS"],
    description: "Highly sought-after college with major tertiary care hospital affiliation.",
    image_url: "https://images.example.com/seth-gs.jpg",
    exam_accepted: "NEET",
    min_rank: 1000,
    max_rank: 5000
  },
  {
    name: "St. John's Medical College",
    location: "Bengaluru",
    state: "Karnataka",
    fees: 1300000,
    rating: 4.5,
    placement_percent: 90,
    courses: ["MBBS", "MD", "MS"],
    description: "Leading private medical college known for ethics and quality training.",
    image_url: "https://images.example.com/st-johns.jpg",
    exam_accepted: "NEET",
    min_rank: 4500,
    max_rank: 18000
  },
  {
    name: "Kasturba Medical College Manipal",
    location: "Manipal",
    state: "Karnataka",
    fees: 1750000,
    rating: 4.6,
    placement_percent: 91,
    courses: ["MBBS", "MD", "MS"],
    description: "Top private medical college with international collaborations.",
    image_url: "https://images.example.com/kmc-manipal.jpg",
    exam_accepted: "NEET",
    min_rank: 3500,
    max_rank: 15000
  },
  {
    name: "Kasturba Medical College Mangalore",
    location: "Mangaluru",
    state: "Karnataka",
    fees: 1700000,
    rating: 4.5,
    placement_percent: 90,
    courses: ["MBBS", "MD", "MS"],
    description: "Strong coastal medical campus with modern diagnostics and teaching.",
    image_url: "https://images.example.com/kmc-mangalore.jpg",
    exam_accepted: "NEET",
    min_rank: 4000,
    max_rank: 17000
  },
  {
    name: "Amrita Institute of Medical Sciences",
    location: "Kochi",
    state: "Kerala",
    fees: 1600000,
    rating: 4.4,
    placement_percent: 89,
    courses: ["MBBS", "MD", "MS"],
    description: "Renowned private institution with advanced super-specialty training.",
    image_url: "https://images.example.com/amrita-medical.jpg",
    exam_accepted: "NEET",
    min_rank: 5000,
    max_rank: 22000
  },
  {
    name: "Sri Ramachandra Medical College",
    location: "Chennai",
    state: "Tamil Nadu",
    fees: 1450000,
    rating: 4.3,
    placement_percent: 87,
    courses: ["MBBS", "BDS", "MD"],
    description: "Comprehensive medical campus with good infrastructure and academics.",
    image_url: "https://images.example.com/sri-ramachandra.jpg",
    exam_accepted: "NEET",
    min_rank: 7500,
    max_rank: 30000
  },
  {
    name: "Bharati Vidyapeeth Medical College Pune",
    location: "Pune",
    state: "Maharashtra",
    fees: 1250000,
    rating: 4.2,
    placement_percent: 85,
    courses: ["MBBS", "MD", "MS"],
    description: "Established private college with broad specialties and clinical training.",
    image_url: "https://images.example.com/bvdu-medical.jpg",
    exam_accepted: "NEET",
    min_rank: 11000,
    max_rank: 42000
  },
  {
    name: "MS Ramaiah Medical College",
    location: "Bengaluru",
    state: "Karnataka",
    fees: 1400000,
    rating: 4.3,
    placement_percent: 86,
    courses: ["MBBS", "MD", "MS"],
    description: "Popular private college with strong hospital network and faculty.",
    image_url: "https://images.example.com/ms-ramaiah.jpg",
    exam_accepted: "NEET",
    min_rank: 9500,
    max_rank: 36000
  },
  {
    name: "DY Patil Medical College Navi Mumbai",
    location: "Navi Mumbai",
    state: "Maharashtra",
    fees: 2000000,
    rating: 4.2,
    placement_percent: 84,
    courses: ["MBBS", "MD", "MS"],
    description: "High-end private medical college with advanced facilities.",
    image_url: "https://images.example.com/dy-patil-medical.jpg",
    exam_accepted: "NEET",
    min_rank: 12000,
    max_rank: 50000
  },
  {
    name: "Narayana Medical College",
    location: "Nellore",
    state: "Andhra Pradesh",
    fees: 1350000,
    rating: 4.1,
    placement_percent: 82,
    courses: ["MBBS", "MD", "MS"],
    description: "Private medical college with steady clinical exposure and outcomes.",
    image_url: "https://images.example.com/narayana-medical.jpg",
    exam_accepted: "NEET",
    min_rank: 14000,
    max_rank: 55000
  },
  {
    name: "SRM Medical College Hospital and Research Centre",
    location: "Chennai",
    state: "Tamil Nadu",
    fees: 1500000,
    rating: 4.1,
    placement_percent: 83,
    courses: ["MBBS", "MD", "MS"],
    description: "Integrated teaching hospital with modern medical infrastructure.",
    image_url: "https://images.example.com/srm-medical.jpg",
    exam_accepted: "NEET",
    min_rank: 13000,
    max_rank: 52000
  },
  {
    name: "JSS Medical College Mysuru",
    location: "Mysuru",
    state: "Karnataka",
    fees: 1300000,
    rating: 4.2,
    placement_percent: 84,
    courses: ["MBBS", "MD", "MS"],
    description: "Well-established medical college with strong postgraduate programs.",
    image_url: "https://images.example.com/jss-medical.jpg",
    exam_accepted: "NEET",
    min_rank: 12500,
    max_rank: 48000
  },
  {
    name: "Saveetha Medical College",
    location: "Chennai",
    state: "Tamil Nadu",
    fees: 1550000,
    rating: 4.1,
    placement_percent: 82,
    courses: ["MBBS", "BDS", "MD"],
    description: "Private deemed university with growing medical research opportunities.",
    image_url: "https://images.example.com/saveetha-medical.jpg",
    exam_accepted: "NEET",
    min_rank: 15000,
    max_rank: 60000
  },
  {
    name: "Dr. D.Y. Patil Medical College Kolhapur",
    location: "Kolhapur",
    state: "Maharashtra",
    fees: 1800000,
    rating: 4.0,
    placement_percent: 80,
    courses: ["MBBS", "MD", "MS"],
    description: "Modern private medical college with broad clinical departments.",
    image_url: "https://images.example.com/dyp-kolhapur.jpg",
    exam_accepted: "NEET",
    min_rank: 17000,
    max_rank: 68000
  },
  {
    name: "Sree Balaji Medical College",
    location: "Chennai",
    state: "Tamil Nadu",
    fees: 1450000,
    rating: 4.0,
    placement_percent: 79,
    courses: ["MBBS", "MD", "MS"],
    description: "Private institution offering strong foundational clinical training.",
    image_url: "https://images.example.com/sree-balaji.jpg",
    exam_accepted: "NEET",
    min_rank: 19000,
    max_rank: 72000
  },
  {
    name: "Krishna Institute of Medical Sciences",
    location: "Karad",
    state: "Maharashtra",
    fees: 1500000,
    rating: 4.0,
    placement_percent: 80,
    courses: ["MBBS", "MD", "MS"],
    description: "Private institute known for discipline and hospital-based learning.",
    image_url: "https://images.example.com/kims-karad.jpg",
    exam_accepted: "NEET",
    min_rank: 18000,
    max_rank: 70000
  },
  {
    name: "MGM Medical College Navi Mumbai",
    location: "Navi Mumbai",
    state: "Maharashtra",
    fees: 1650000,
    rating: 4.0,
    placement_percent: 81,
    courses: ["MBBS", "MD", "MS"],
    description: "Known private college with balanced academics and patient exposure.",
    image_url: "https://images.example.com/mgm-medical.jpg",
    exam_accepted: "NEET",
    min_rank: 20000,
    max_rank: 76000
  },
  {
    name: "Rajarajeswari Medical College",
    location: "Bengaluru",
    state: "Karnataka",
    fees: 1400000,
    rating: 3.9,
    placement_percent: 78,
    courses: ["MBBS", "MD", "MS"],
    description: "Private medical college with improving infrastructure and outcomes.",
    image_url: "https://images.example.com/rrmc.jpg",
    exam_accepted: "NEET",
    min_rank: 22000,
    max_rank: 85000
  },
  {
    name: "Sharda University School of Medical Sciences",
    location: "Greater Noida",
    state: "Uttar Pradesh",
    fees: 1700000,
    rating: 3.9,
    placement_percent: 77,
    courses: ["MBBS", "MD", "MS"],
    description: "Large private campus with integrated teaching hospital.",
    image_url: "https://images.example.com/sharda-medical.jpg",
    exam_accepted: "NEET",
    min_rank: 26000,
    max_rank: 92000
  },
  {
    name: "Teerthanker Mahaveer Medical College",
    location: "Moradabad",
    state: "Uttar Pradesh",
    fees: 1350000,
    rating: 3.8,
    placement_percent: 75,
    courses: ["MBBS", "MD", "MS"],
    description: "Private medical college offering broad undergraduate medical education.",
    image_url: "https://images.example.com/tmims.jpg",
    exam_accepted: "NEET",
    min_rank: 30000,
    max_rank: 110000
  },
  {
    name: "Hamdard Institute of Medical Sciences",
    location: "New Delhi",
    state: "Delhi",
    fees: 1450000,
    rating: 4.0,
    placement_percent: 79,
    courses: ["MBBS", "MD", "MS"],
    description: "Delhi-based private medical institute with strong urban clinical exposure.",
    image_url: "https://images.example.com/hamdard-medical.jpg",
    exam_accepted: "NEET",
    min_rank: 21000,
    max_rank: 80000
  }
];

async function main() {
  await prisma.college.deleteMany();
  await prisma.college.createMany({
    data: colleges
  });
  console.log(`Seeded ${colleges.length} colleges`);
}

main()
  .catch((error) => {
    console.error("Seeding failed:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
